version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-sample"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1tj8dunlulih2"
s3_prefix = "sam-sample"
region = "ap-northeast-1"
profile = "default"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = ["HelloWorldFunction=262334296846.dkr.ecr.ap-northeast-1.amazonaws.com/samsample1a37ddc0/helloworldfunction19d43fc4repo"]
